USB_VID = 0x1209
USB_PID = 0x6571
USB_PRODUCT = "MRBW-WIFI v1"
USB_MANUFACTURER = "Iowa Scaled Engineering"

IDF_TARGET = esp32s2

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

# The default queue depth of 16 overflows on release builds,
# so increase it to 32.
CFLAGS += -DCFG_TUD_TASK_QUEUE_SZ=32

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=40m
CIRCUITPY_ESP_FLASH_SIZE=4MB

CIRCUITPY_MODULE=wrover
CIRCUITPY_AUDIOIO=0
CIRCUITPY_ROTARYIO=0
CIRCUITPY_TOUCHIO=0
CIRCUITPY_SHARPDISPLAY=0
CIRCUITPY_SYNTHIO=0
CIRCUITPY_USB_HID=0
CIRCUITPY_USB_MIDI=0
CIRCUITPY_ZLIB=0
